version: '3.8'

services:
  bot:
    restart: always
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    command: python3 bot.py
    depends_on:
      - classifier
  classifier:
    restart: always
    build:
      context: .
      dockerfile: ./classifier/Dockerfile
    command: bentoml serve service:Classification
